#!/bin/sh
declare -r TEMP=trans-temp-mod
declare -r ALL=all-temp-mod.cafe
declare -r INIT=temp-init.cafe
declare -r CAFE2MAUDE=./cafeOBJ2maude.maude
declare -r MAUDE=/Applications/maude-darwin/maude.darwin64
declare -r PARSER=./parser.jar
rm -f $ALL
rm -f $TEMP
rm -f $INIT
for (( i=1; i<=$#; i++ ))
do
   eval arg=\$$i
   cat $arg >> $ALL
done
echo "loop cafe2maude-init ." >> $INIT
java -jar $PARSER $ALL $TEMP
$MAUDE full-maude.maude $CAFE2MAUDE $INIT $TEMP
rm -f $ALL
rm -f $TEMP
rm -f $INIT