#!/bin/sh
declare -r TEMP=trans-temp-mod
declare -r ALL=all-temp-mod.cafe
declare -r MFE=./mfe/mfe.maude
declare -r MAUDE=/Applications/maude-darwin/maude.darwin64
declare -r PARSER=./parser.jar
rm -f $ALL
rm -f $TEMP
for (( i=1; i<=$#; i++ ))
do
   eval arg=\$$i
   java -jar $PARSER $arg $TEMP
   cat $TEMP >> $ALL
done
$MAUDE $MFE $ALL
rm -f $ALL
rm -f $TEMP