#!/bin/sh
declare -r TEMP=trans-temp-mod
declare -r ALL=all-temp-mod.cafe
declare -r MAUDE=/Applications/maude-darwin/maude.darwin64
declare -r LOADTIME=1792
rm -f $ALL
rm -f $TEMP
STARTTIME=$(gdate +%s%3N)
for (( i=1; i<=$#; i++ ))
do
   eval arg=\$$i
   cat $arg >> $ALL
done
echo "\nquit\n" >> $ALL
STARTTIME=$(gdate +%s%3N)
$MAUDE ./citp/citp.maude $ALL
ENDTIME=$(gdate +%s%3N)
echo "Execution time $(($ENDTIME - ($STARTTIME + $LOADTIME))) milliseconds."
rm -f $ALL
rm -f $TEMP