#!/bin/sh
declare -r TEMP=trans-temp-mod
declare -r ALL=all-temp-mod.cafe
declare -r CITP=/Users/adrian/Dropbox/jaist13/CafeOBJ+citp/ui.maude
declare -r MAUDE=/Applications/maude-darwin/maude.intelDarwin
declare -r PARSER=/Users/adrian/Dropbox/jaist13/CafeOBJ+citp/parser.jar
rm -f $ALL
rm -f $TEMP
for (( i=1; i<=$#; i++ ))
do
   eval arg=\$$i
   cat $arg >> $ALL
done
java -jar $PARSER $ALL $TEMP
$MAUDE $CITP $TEMP
rm -f $ALL
rm -f $TEMP