fmod 3TUPLE {C1 :: TRIV, C2 :: TRIV, C3 :: TRIV} is
    sort 3Tuple .

    op <<_;_;_>> : C1$Elt C2$Elt C3$Elt -> 3Tuple [ctor prec 0] .
    op 1*_ : 3Tuple -> C1$Elt [prec 15] .
    op 2*_ : 3Tuple -> C2$Elt [prec 15] .
    op 3*_ : 3Tuple -> C3$Elt [prec 15] .

    var e1 : C1$Elt .
    var e2 : C2$Elt .
    var e3 : C3$Elt .

    eq (1* (<< e1 ; e2 ; e3 >>)) = e1 .
    eq (2* (<< e1 ; e2 ; e3 >>)) = e2 .
    eq (3* (<< e1 ; e2 ; e3 >>)) = e3 .
endfm